name = "roundabout"
version = "0.5.0"

description = "A routes generator"
licences = ["MIT"]
repository = { type = "github", user = "sporto", repo = "gleam-roundabout" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
simplifile = ">= 2.3.1 and < 3.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
justin = ">= 1.0.1 and < 2.0.0"
birdie = ">= 1.5.2 and < 2.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"
glam = ">= 2.0.3 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.9.0 and < 2.0.0"
