name = "examples"
version = "1.0.0"
description = "Route generation example"

[dependencies]
roundabout = { path = ".." }
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
